sonar.projectKey=maus-inc_mauscode
sonar.organization=maus-inc
sonar.projectName=mausCode
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
